# -*- coding: utf-8 -*-
"""2. multicollinearity detection and remedy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCHXj9WiOCqf_pytrd3sOSdxRQMUidSI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()

data

print(data.DESCR)

data.data

data.feature_names

df = pd.DataFrame(data.data, columns = data.feature_names)

df.head()

df['Price'] = data.target  # aaisgn the target

df

#multicollinearity >> when one feature is explained by all other features(more than 2)
#when two features>> correlation
#when more than two features>> multicollinearity>> clustermap, VIF

df.corr() # it shows the correlation

sns.heatmap(df.corr(), annot = True, vmin = -1, vmax = 1)   # annot = True to get the correlation value in the plot itself
#vmin = -1, vmax = 1 this is a correlation colour range

#clustermap table shows group(cluster) relationship

plt.figure(figsize = (4, 5))
sns.clustermap(df.corr(), vmin = -1, vmax = 1, annot=True)
plt.show()  # ye har column main kitna correlation hai  vo dikhat ahai and uske bad uss do column agle column ke sath correlation dikhate hai
# uss line ko ham dendogram kehte hai

#problem with the above plot interpretation>> you understand the relationship among features together
#but don't understand how much>>lack of quantitative measure, so we study vif



# hame ye dikh ke correlation ahi but kita hai vo nihi samjha
# vo samjhne ke liye we have (variance_inflation_factor) vif

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["Feature"] = df.columns

vif['VIF'] =[ variance_inflation_factor(df.values, i) for i in range(len(df.columns))]

vif

#if vif > 10, drop the features one by one>> here highest is Longitude, we will drop this and then again
#calculate vif and then again drop the highest one

df1 = df.copy()

df1

df1.drop("Longitude", axis=1, inplace=True)

df1

vif = pd.DataFrame()
vif["Feature"] = df1.columns
vif['VIF'] =[ variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

vif

df1.drop("AveRooms", axis=1, inplace=True)

vif = pd.DataFrame()
vif["Feature"] = df1.columns
vif['VIF'] =[ variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]
vif

df1.drop("Latitude", axis=1, inplace=True)

vif = pd.DataFrame()
vif["Feature"] = df1.columns
vif['VIF'] =[ variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]
vif

#now all the features vif is below 10, so we can build the model

df

X = df1.iloc[:, :-1] #independent variable
y = df1.iloc[:, -1] #target variable

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

X_train

y_train

#scaling(optionaal) can be done after train test split

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler

#fit_transform is used for train data
#transform is used for test data

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

X_test

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

model.fit(X_train, y_train)

model.coef_

model.intercept_

y_pred = model.predict(X_test)

y_pred

#performance metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(np.sqrt(mean_squared_error(y_test, y_pred)))
print(r2_score(y_test, y_pred))

score = r2_score(y_test, y_pred)
score

#internal homework
#adjusted rsquare
1 - ((1-score)*len(y_test)-1) /  ((len(y_test)) - X_test.shape[1]-1)

#here the no of features were low, thats why you dropped the features one by one and checked each time
#what if the no of features are 1000 in number
#implementation using RFE(Recursive Feature Elimination)

X = df.iloc[:, :-1] #iv
y = df.iloc[:, -1] #dv

X

y

X.columns

from sklearn.feature_selection import RFE

rfe = RFE(LinearRegression(), n_features_to_select=5)
rfe

rfe.fit(X, y)

rfe.support_

X.columns

rfe.ranking_

rfe.predict(X) #since the train split was not done, so use X directly

