# -*- coding: utf-8 -*-
"""6. Simple Linear Regression Python Implementation - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108h8MF6nrqcLOVTtepZ7i3hzP6RxCfOi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#reading the data
#here we are loading the data from scikit learn
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

diabetes

#Problem statement: To predict disease progression one year after baseline provided 10 features
#in one year how the sugar level has changed

print(diabetes.DESCR)

diabetes

diabetes.data

diabetes.target

diabetes.feature_names

data = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)

data.head()

data['target'] = diabetes.target

data

#EDA, DATACLEANING, DATAPREPARATION, FEATURE ENGINEERING

X = data[["bmi"]] #one indepenedent variable
y = data['target'] #dependent variable

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=2)
#reandom_state when fixed helps us to reproduce the same result again and again

X_train.shape

X_train

X_test

y_train

y_test

#scaling(optional)

#model training
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model

X_train

y_train

#training of model
model.fit(X_train, y_train)
#at the backend it will use gradient descent to give optimal coefficient

model.coef_ #attribute of the model

model.intercept_

y_pred = model.predict(X_test)

y_pred

#visualise the result
plt.scatter(X_test, y_test, color = 'black', label = "Actual")
plt.plot(X_test, y_pred, color = 'blue', linewidth = 3, label = "Predicted linear regression line")
plt.xlabel("BMI")
plt.ylabel("One year progression target")
plt.title("Linear regression on diabetes data")
plt.legend()
plt.show()

#model evaluation
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

