# -*- coding: utf-8 -*-
"""6. Simple Linear Regression Python Implementation - 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUK1rAHoGhpT-5megJqaOmoYrusDBTNV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#read the dataset
df = pd.read_csv("height-weight.csv")

df

df.head()

plt.scatter(df.Weight, df.Height)
plt.xlabel("weight")
plt.ylabel("Height")
plt.show()

#Problem statement>> I want to predict height based on weight

#divide the data into X and y
X = df[["Weight"]]
y = df["Height"]

X

y

#train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=1)

X_train

X_test

y_train

y_test

X_train.shape, X_test.shape, y_train.shape, y_test.shape

#scaling(optional) >> standardization>> fit_transform on train data and transform on test data
#if you use fit on test data, (that is wrong) you are doing data leakage, avoid it
#most of the ml model standardscaler is used as it deals with normal distribution

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler

X_train

X_test

#scaling should be done always after train test split
#target variableshould not be scaled
#avoid scaling categorical features
X_train = scaler.fit_transform(X_train) #for train data use fit_transform
X_test = scaler.transform(X_test) #for test data use transform

X_test

X_train

X_test

#scaling is optional >> why because it doen't affect the distribution of the data
plt.scatter(X_train, y_train)

#model training
from sklearn.linear_model import LinearRegression

#linear regression parameters
#fit_intercept >> The best fit line will have intercept, by default it is true
#copy_X >> copy the original X_train and then build the model, it will not modify the original data
#n_jobs >>-1 means using all processors.
#positive>> When set to True, forces the coefficients to be positive.

#fit>> train the model
#predict>> test the model

#after building the model, you have attributes of the model
#coef_
#intercept

regressor = LinearRegression()

regressor

regressor.fit(X_train, y_train)

regressor.coef_

regressor.intercept_

print("The slope or coeff of model is ", regressor.coef_)
print("The intercept of the model is ", regressor.intercept_)

#prediction on train data
#interpretation of coef>> one unit increase in weight, on average the height increase by 17.73 units
#predicted height(y) on Xtrain = 160 + 17.73 * (Xtrain)

#predicted height(y) on Xtest = 160 + 17.73 * (Xtest)

#prediction on train
regressor.predict(X_train)

plt.scatter(X_train, y_train)
plt.plot(X_train, regressor.predict(X_train), 'r')

y_pred_test = regressor.predict(X_test)

y_pred_test

y_pred_test, y_test

plt.scatter(X_test, y_test)
plt.plot(X_test, regressor.predict(X_test), 'r')

#performance metrics

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mean_absolute_error(y_test, y_pred_test)

mean_squared_error(y_test, y_pred_test)

rsq = r2_score(y_test,y_pred_test) #rsquare = 1-SSR/SST
rsq

#adjusted rsquare
#adjusted R2  = [1-(1-rsquare)*n-1/(n-k-1)] #n is no of observation and k is no of predictor variables

X_test.shape[1]

1-(1-rsq)*(len(y_test)-1)/(len(y_test)-X_test.shape[1] - 1)
#adjusted rsquare will be lesser than r square

#assumption
#X-y should have linear relationship
#Observation should have no relation
#error should have constant variation
#error should be normally distributed
#features among themself should be least related

plt.scatter(y_test, y_pred_test)
#to chck if y_test and its prediction alighns

#error should have constant variation
#error should be normally distributed

error = y_test-y_pred_test
error

import seaborn as sns
sns.distplot(error) #approximately a normal distribution

#to check constant variance
plt.scatter(error, y_pred_test)

