# -*- coding: utf-8 -*-
"""Pickling of models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Ig98I2fkXKSaj2gO5oymE88i6_wjyIz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# its warnigs
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()

data

print(data.DESCR)

#Problem statement>> To predict the median house value for California districts

data.keys()

data.target_names

data.data

data.feature_names

##dataframe
df = pd.DataFrame(data.data, columns = data.feature_names)

df

df['Price'] = data.target

df

#EDA, Data Preparation

df.dtypes

df.info()

df.isnull().sum()

df.head()

df.tail()

df.sample()

df.describe()

df.corr()

sns.heatmap(df.corr(), annot = True)

#separate X and y
X=df.iloc[:, :-1] #independent variable
y = df.iloc[:, -1]

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=1)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

#scaling(optional)

#y should not be scaled
#fit transform on train data
#transform on test data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

X_test

#model training
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model

model.fit(X_train, y_train)

X_train.shape

model.coef_

len(model.coef_)

model.intercept_

y_pred = model.predict(X_test)

y_pred

#performance metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

rsq = r2_score(y_test, y_pred)

#adjusted r square
1-(1-rsq) * (len(y_test)-1) / (len(y_test) - X_test.shape[1] - 1)

#assumption
plt.scatter(y_test, y_pred)

error = y_test-y_pred

sns.distplot(error)

#homoscedastity>>constant variance between y_pred and error (y axis)

plt.scatter(y_pred, error)

"""#pickle>> allows you to store the python object on the disk

Python pickle module is used for serializing and de-serializing a Python object structure. Any object in Python can be pickled so that it can be saved on disk. What pickle does is that it “serialises” the object first before writing it to file. Pickling is a way to convert a python object (list, dict, etc.) into a character stream. The idea is that this character stream contains all the information necessary to reconstruct the object in another python script

#serialization :  Serialization is the process of converting a data structure or object into a format that can be easily stored, transmitted, or persisted. During serialization, the object's state is converted into a stream of bytes or other formats that can be written to disk, sent over a network, or stored in memory

#Deserialization>>Deserialization is the process of reconstructing a serialized object back into its original form. During deserialization, the serialized data is read and converted back into a data structure or object that matches the original.
"""

import pickle

model
# here we use the file handling which is open
pickle.dump(model, open("model.pkl", "wb")) #write binary mode
#python's object (model), its attributes and methods are converted into bytes stream

model = pickle.load(open("model.pkl", "rb")) # yaha hamne tarien model us kiya hai past ka lineregression wala
# already trained model load kar rahe hai matlab client ke side main use kar rahe hai
model.predict(X_test)




# hamne ik model build kiya hai and usse hame client ke machine pe run karna hai 
#how will the run?
# to pickel kyakarta hai model ko DISK main store karta hai
# nad then network ke through vo kisi ko bhi send kar sakte hai 
#pickel module help karta hai disk ppe store karne ke liye
# and  ham model ko dump karenge and fir diskpe store karenge 
# and client ke site pe firse load karenge
# isase hame firse model ko train karne ki jarurat nahi hai
# pickel usko binary format main karta hai isase transfer,store or persist  esily ho jata hai
